server:
  port: 9100
  servlet:
    context-path: /tabs

spring:
  profiles:
    active: out

myatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tiankong44.tool
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'


logging:
  level:
    root: info
    com.tiankong44.tool.mapper: debug


privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIjqo6zrMlQ9ToqeoiFP3RKcJ4Luxmcf2nVxjMGvsE9Kj1kw9JCHDE8I8Gv2CqglfbX9itSg2CvmbOuJzxm0KYjG5aPMswOVLQp1ZOJm0PXlyehQECcwqemHtsJ6K+5REkCLJ1v9vt1I6KKQBRrPIJGd1CwZp3bJYvW45fLnNB4/AgMBAAECgYA7NNwahop5CxnPr9GEfjinN4eOgxqgtZGOf8/SYdroLuHWO+lGJmAYPVFaHkd1duDptf42/Gb+dOJc6Hb6MoJS0AuWc2C6I0psv9gGqVkL9noEYQpL5Qx9KxDH3MvccBDNnrOQwHFZikd31E+FHqvVaYMs+R78wysV0kc/CEqbwQJBAPHpDmI65J/QJUWTyVip3b98Z9tXXPM4TZb8HDW9aUjL9rAQ7G600wQY2qmSa1z1TVpb5+odMSgsE7/G4VaDL8cCQQCQ5Blq+4WTOLChHzGvc5yLRpMb4jCJm6XFv+89tqpbqFZcuJFqPLdiQCuqHL+41f4nbO8y79ws1RlHqgXmBY3JAkBD9H4P5g9XPXda5jsHZyBdrCrYmOAJiuVw5n1eM0kiI/m2V+qy5qToX7r9K55xTI9gNLUfNPgcGtWpZ8rhLJT9AkA7GiBYKGMzS4OZJa1RwVoQ4efuDtT3vNrhEErZpKJXIxKfXdZLPJsdY8mr6XA3SGsUz/W+lGL+kqpuNieTzZ4pAkEAgtabJTIQQ9B2GsU11gfzwvZU62pH/3LjQPyVQnkgyWNtiNQ7eVayPoeeRozV1czOw2QkDXuq4bH3SxHPSwFYfw==
publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCI6qOs6zJUPU6KnqIhT90SnCeC7sZnH9p1cYzBr7BPSo9ZMPSQhwxPCPBr9gqoJX21/YrUoNgr5mzric8ZtCmIxuWjzLMDlS0KdWTiZtD15cnoUBAnMKnph7bCeivuURJAiydb/b7dSOiikAUazyCRndQsGad2yWL1uOXy5zQePwIDAQAB
sign: c7Tp9DOC/vezz/rz2thuDKc0o1q/TmJYryZ0FPYoK+29LAeLMdfoJvl+db7vcabbF3MCruRDd+fbFIj5ywcs+lcmbnM0vSVEw0ArznFI4ZatTRTPyvHRybQrCZMxcg7rk6yNX/87sIvrZVpFn/FHXa3ZwlLBkn8D2qTW7q1hnuw=
